# PR Labeler documentation: https://github.com/marketplace/actions/labeler

dependencies:
  - '.github/dependabot.yml'
  - '**/go.mod'
  - '**/go.sum'
documentation:
  - '**/*.md'
  - 'docs/**/*'
  - 'examples/**/*'
linter:
  - '.github/workflows/*-lint.yml'
  - '.golangci.yml'
provider:
  - '.go-version'
  - 'gitlab/**/*'
  - 'main.go'
tests:
  - '**/*_test.go'
tools:
  - 'tools/**/*'
  - 'scripts/**/*'
  - 'GNUMakefile'
workflows:
  - '.github/**/*'
