# GitHub Action reference: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
#
# Automated handling of stale issues and pull requests.
#
# NOTE: When changing "days-before-*" values, please also update the "stale-issue-message" and/or
# "stale-pr-message" values.

name: stale

on:
  schedule:
    #        ┌───────────── minute (0 - 59)
    #        │ ┌───────────── hour (0 - 23)
    #        │ │ ┌───────────── day of the month (1 - 31)
    #        │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #        │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #        * * * * *
    - cron: '8 3 * * *'

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v5
        with:
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
          stale-issue-message: |
            Marking this issue as stale due to 120 days of inactivity. If this issue receives no comments in the next 30 days it will be closed. Maintainers can also remove the `stale` label.
            
            Please comment with more information if you would like this issue to remain open.
          stale-pr-message: |
            Marking this pull request as stale due to 30 days of inactivity. If this pull request receives no comments in the next 14 days it will be closed. Maintainers can also remove the `stale` label.
            
            To help this pull request get reviewed, please check that it is rebased onto the latest ${{ github.event.repository.default_branch }} and is passing automated checks. It also helps if you could reference an issue that the pull request resolves, and create one if it doesn't exist.
          close-issue-message: 'This issue was closed because it has been stale for 30 days with no activity.'
          close-pr-message: 'This PR was closed because it has been stale for 14 days with no activity.'
          days-before-issue-stale: 120
          days-before-pr-stale: 30
          days-before-issue-close: 30
          days-before-pr-close: 14
          exempt-issue-labels: keep-open,bug,enhancement,documentation
