# https://github.com/bflad/tfproviderlint

name: tfproviderlint

on: [push,pull_request]

jobs:
  tfproviderlint:
    name: tfproviderlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2.1.3
      - run: make tfproviderlint
