name: Unit Tests
on: [push,pull_request]

jobs:
  vendor-check:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15

      - name: Check out code repository source code
        uses: actions/checkout@v2

      - name: Run vendor-check
        run: make vendor-check

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        go: [1.14, 1.15]
        os: [ubuntu-latest, macos-latest, windows-latest]
        make_target: [test, vet]

    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Check out code repository source code
      uses: actions/checkout@v2

    # https://help.github.com/en/actions/reference/workflow-commands-for-github-actions
    - name: Set build variables
      run: |
        echo "MAKE_TARGET=${{ matrix.make_target }}" >> $GITHUB_ENV
        echo "GO_FLAGS=-mod=vendor" >> $GITHUB_ENV
        echo "GO111MODULE=on" >> $GITHUB_ENV

    - name: Run ${{matrix.make_target}}
      run: |
        make $MAKE_TARGET
