name: Unit Tests
on: [push,pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        go: [1.15, 1.16]
        os: [ubuntu-latest, macos-latest, windows-latest]
        make_target: [test]

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2.1.3
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Check out code repository source code
      uses: actions/checkout@v2

    # https://help.github.com/en/actions/reference/workflow-commands-for-github-actions
    - name: Set build variables
      run: |
        echo "MAKE_TARGET=${{ matrix.make_target }}" >> $GITHUB_ENV
        echo "GO111MODULE=on" >> $GITHUB_ENV

    - name: Run ${{matrix.make_target}}
      run: |
        make $MAKE_TARGET
